In [1]:
## Завдання №1: Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та 
## виведіть його значення.

import numpy as np

a = np.arange(1, 11)

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
## Завдання №2: Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та 
## виведіть його значення.

zero = np.zeros((3, 3), dtype=int)

print(zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [3]:
## Завдання №3: Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 
## та виведіть його значення.

n = np.random.randint(1, 11, (5, 5))

print(n)

[[ 7  3  4 10  1]
 [ 7  2  9  7  5]
 [ 7  2  4  2  6]
 [ 9  1 10  4  8]
 [ 3  2 10  7  9]]


In [4]:
## Завдання №4: Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 
## та виведіть його значення.

m = np.random.rand(4, 4)

print(m)

[[0.05185003 0.74845175 0.21829247 0.56629209]
 [0.76689112 0.49560471 0.15072902 0.31761188]
 [0.70397252 0.18200561 0.71860053 0.99539653]
 [0.89147095 0.38425931 0.64138477 0.08093291]]


In [5]:
## Завдання №5: Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні 
## від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)

print("Перший масив:", array1)
print("Другий масив:", array2)

print("Результат додавання:", array1 + array2)
print("Результат віднімання:", array1 - array2)
print("Результат множення:", array1 * array2)

Перший масив: [ 5  6  7  1 10]
Другий масив: [8 1 7 8 2]
Результат додавання: [13  7 14  9 12]
Результат віднімання: [-3  5  0 -7  8]
Результат множення: [40  6 49  8 20]


In [6]:
## Завдання №6: Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

x = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.array([7, 6, 5, 4, 3, 2, 1])

print(np.dot(x, y))

84


In [7]:
## Завдання №7: Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні 
## від 1 до 10 та перемножте їх між собою.

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)

print("Результат множення матриць:\n", np.dot(matrix1, matrix2))

Перша матриця:
 [[ 5 10]
 [ 2  8]]
Друга матриця:
 [[10  7  4]
 [ 2  2  1]]
Результат множення матриць:
 [[70 55 30]
 [36 30 16]]


In [8]:
## Завдання №8: Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 
## та знайдіть її обернену матрицю.

matrix3 = np.random.randint(1, 11, (3, 3))
matrix3_inv = np.linalg.inv(matrix3)

print("Матриця:\n", matrix3)
print("Обернена матриця:\n", matrix3_inv)

Матриця:
 [[ 2  9  3]
 [10  8 10]
 [ 5  3 10]]
Обернена матриця:
 [[-0.13157895  0.21315789 -0.17368421]
 [ 0.13157895 -0.01315789 -0.02631579]
 [ 0.02631579 -0.10263158  0.19473684]]


In [9]:
## Завдання №9: Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 
## та транспонуйте її.

matrix4 = np.random.rand(4, 4)
matrix4_trans = matrix4.T

print("Матриця:\n", matrix4)
print("Транспонована матриця:\n", matrix4_trans)

Матриця:
 [[0.6764785  0.50050008 0.10567565 0.28463525]
 [0.58838557 0.98344434 0.52351802 0.60561652]
 [0.96450185 0.73678349 0.98937338 0.60812427]
 [0.6850206  0.6812256  0.67344006 0.0695965 ]]
Транспонована матриця:
 [[0.6764785  0.58838557 0.96450185 0.6850206 ]
 [0.50050008 0.98344434 0.73678349 0.6812256 ]
 [0.10567565 0.52351802 0.98937338 0.67344006]
 [0.28463525 0.60561652 0.60812427 0.0695965 ]]


In [10]:
## Завдання №10: Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами 
## в діапазоні від 1 до 10 та перемножте матрицю на вектор.

matrix5 = np.random.randint(1, 11, (3, 4))
c = np.random.randint(1, 11, 4)

print("Матриця:\n", matrix5)
print("Вектор:\n", c)
print("Результат:\n", np.dot(matrix5, c))

Матриця:
 [[ 8  1  2  2]
 [10  7 10  8]
 [ 9  2  8  9]]
Вектор:
 [8 6 4 2]
Результат:
 [ 82 178 134]


In [11]:
## Завдання №11: Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами 
## в діапазоні від 0 до 1 та перемножте матрицю на вектор.

matrix6 = np.random.rand(2, 3)
d = np.random.rand(3)

print("Матриця:\n", matrix6)
print("Вектор:\n", d)
print("Результат:\n", np.dot(matrix6, d))

Матриця:
 [[0.73721445 0.5044351  0.10417486]
 [0.56568665 0.5166567  0.32851944]]
Вектор:
 [0.72761897 0.6712787  0.34634723]
Результат:
 [0.91110843 0.87220677]


In [12]:
## Завдання №12: Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 
## 10 та виконайте їхнє поелементне множення.

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)

print("Результат поелементного множення матриць:\n", matrix1 * matrix2)

Перша матриця:
 [[7 9]
 [9 1]]
Друга матриця:
 [[1 8]
 [6 4]]
Результат поелементного множення матриць:
 [[ 7 72]
 [54  4]]


In [13]:
## Завдання №13: Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 
## 10 та знайдіть їх добуток.

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)

print("Результат поелементного множення матриць:\n", np.dot(matrix1, matrix2))

Перша матриця:
 [[1 3]
 [2 6]]
Друга матриця:
 [[9 9]
 [5 7]]
Результат поелементного множення матриць:
 [[24 30]
 [48 60]]


In [14]:
## Завдання №14: Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 
## та знайдіть суму елементів матриці.

matrix = np.random.randint(1, 101, (5, 5))

print("Матриця:\n", matrix)
print("Сума елементів матриці:\n", matrix.sum())

Матриця:
 [[35 42 44 73 88]
 [95  7 20  2  9]
 [91 23 82 70  8]
 [28 72 31 59 20]
 [57 98 45 17 48]]
Сума елементів матриці:
 1164


In [15]:
## Завдання №15: Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 
## 10 та знайдіть їхню різницю.

matrix1 = np.random.randint(1, 11, (4, 4))
matrix2 = np.random.randint(1, 11, (4, 4))

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)

print("Різниця матриць:\n", matrix1 - matrix2)

Перша матриця:
 [[ 4  7  3  8]
 [ 5 10  1  8]
 [ 8  1  5  3]
 [ 2  1  1  8]]
Друга матриця:
 [[ 5 10  3  4]
 [ 2  5  2  7]
 [ 7  7  7  5]
 [ 9  4  5  5]]
Різниця матриць:
 [[-1 -3  0  4]
 [ 3  5 -1  1]
 [ 1 -6 -2 -2]
 [-7 -3 -4  3]]


In [16]:
## Завдання №16: Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 
## та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

matrix = np.random.random((3, 3))
row_sums = np.sum(matrix, axis=1, keepdims=True)

print("Матриця:\n", matrix)
print("Вектор-стовпчик, що містить суму елементів кожного рядка матриці:\n", row_sums)

Матриця:
 [[0.57464158 0.3599061  0.93506088]
 [0.99319779 0.04704135 0.72306536]
 [0.86240186 0.03878247 0.06488162]]
Вектор-стовпчик, що містить суму елементів кожного рядка матриці:
 [[1.86960856]
 [1.76330449]
 [0.96606595]]


In [17]:
## Завдання №17: Створіть матрицю розміром 3x4 з довільними цілими числами і створіть матрицю з квадратами цих 
## чисел.

matrix = np.random.randint(-100, 100, (3, 4))

print("Матриця:\n", matrix)
print("Матриця з квадратами чисел v1:\n", np.square(matrix))
print("Матриця з квадратами чисел v2:\n", matrix ** 2)
print("Матриця з квадратами чисел v3:\n", matrix * matrix)

Матриця:
 [[ 63 -86 -72  98]
 [  2 -50  97  62]
 [-13 -49  99  73]]
Матриця з квадратами чисел v1:
 [[3969 7396 5184 9604]
 [   4 2500 9409 3844]
 [ 169 2401 9801 5329]]
Матриця з квадратами чисел v2:
 [[3969 7396 5184 9604]
 [   4 2500 9409 3844]
 [ 169 2401 9801 5329]]
Матриця з квадратами чисел v3:
 [[3969 7396 5184 9604]
 [   4 2500 9409 3844]
 [ 169 2401 9801 5329]]


In [18]:
## Завдання №18: Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 
## та знайдіть вектор з квадратними коренями цих чисел.

m = np.random.randint(1, 51, 4)

print("Вектор:\n", m)
print("Вектор з квадратними коренями v1:\n", np.sqrt(m))
print("Вектор з квадратними коренями v2:\n", m ** 0.5)

Вектор:
 [14 46 38  6]
Вектор з квадратними коренями v1:
 [3.74165739 6.78232998 6.164414   2.44948974]
Вектор з квадратними коренями v2:
 [3.74165739 6.78232998 6.164414   2.44948974]
